[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "bequem"
authors = [
  {name = "Matthias Deiml", email = "matthias.deiml@uni-a.de"},
]
version = "0.0.0"
description = "A tool to construct and simulate block encodings for quantum computation"
keywords = ["quantum computing"]
dependencies = [
  "tequila-basic@git+ssh://git@github.com/Ram4Dev/tequila@f46eae9e415efe643ab62fcec70743d6f2d5ced5",
  "rich==14.0.*",
  "qiskit==2.0.2",
  "cirq==1.5.0"
]


[project.urls]
Repository = "https://github.com/bequem-py/bequem.git"

[tool.pytest.ini_options]
addopts = [
  "--import-mode=importlib",
]
pythonpath = ["src"]
